### PR TITLE
Scribblemax node scribbletune template

### PR DESCRIPTION
**Pull request by JanZaion**
Since the release of 4.0, I've been working a lot with Scribbletune in Max for Live and I wanted to contribute. I hope that pull request to this repo is the right way to go about it.

TL;DR: this is a template for creating Scribbletune patches in M4L while running the scripting logic in Node for Max. Anyone can download the .amxd file and start working on their patch without ever needing to run it through Webpack.

Detailed description: I am by no means saying that this is the best way or the only way of working with Scribbletune in M4L. There are 2 types of javascript objects in M4L: js object and node.script object. Js object is great for interacting with Live's API, but it runs on a very dated engine and does not support javascript features past ES5. Node.script runs on the implemented version of Node, which means it can run modern javascript and do Node stuff, including the use of Node packages. That is pretty great in my opinion, the problem is that the Node.script has a very limited capabilities when it comes to interacting with Live's API.

To get the best of both objects, I've created the scribblemax-node-scribbletune-template.amxd file (sorry for the stupidly long name). It contains a basic presentation setup with 2 live.menu objects that send parameters to a dictionary object. Then there is a node.script object that retrieves these parameters from the dictionary. In this script, Scribbletune "vanilla" is required and the Scribbletune clip is made. All the javascript logic  for the creation of Scribbletune clip can be written here. The clip is exported to another dictionary object. Finally, a js object containing a packaged version of Scribblemax retrieves the Scribbletune clip from the dictionary. The script then passes the clip down to Live's API just as it would in Riff.

Since the .amxd file is frozen, anyone should be able to download it and start writing their musical scripts without the need to touch Webpack or even install NPM packages. I have included all the scripts that are inside of the frozen .amxd file for those who want to maintain control over the whole process.

I am open to any clarification or improvement of the code, should the need arise.

Scribbletune is awesome!

### CODE REVIEW

**Comment by walmik** [comment]
@JanZaion Thank you for this PR.. it looks really interesting! I think i m gonna take some time to wrap my head around it to understand it fully. Will get back to you once I go over it in detail.

**Comment by walmik** [comment]
Hello @JanZaion I cloned your branch today to try out this feature. Maybe i m missing something but I dont see anything generated via scribblemax-node-scribbletune-template amxd (i dropped it on a MIDI channel in Ableton Live 10) and clicked makeClip. In the max console I could see `node.script: Node script not running, can't handle message makeClip`

If I unfreeze the device (for debugging) I get the message `node.script: Could not locate file at path nodeScribbletune.js`

Can you share some steps on how to checkout this feature? Can you please try this by cloning your own branch in some other location on your computer and directly try to use dist/scribblemax-node-scribbletune-template amxd?

**Comment by JanZaion** [comment]
Sorry about that... I've probably packaged it incorrectly. I will try to replicate this bug and fix the patch.

**Comment by walmik** [comment]
Sure @JanZaion 
In the mean time, could you help me understand the feature you re proposing. At a high level, is your goal to enable JS developers to somehow use only the `clip` method within Ableton Live?

Typically if I didnt use maxforlive, 
1. I d have to write a JS script which defines a clip and a MIDI method like this
```
const scribble = require('scribbletune');
const clip = scribble.clip({
	notes: scribble.scale('C4 major'),
	pattern: 'x_'.repeat(8),
	subdiv: '16n',
	// rest of the parameters of the clip method
});

scribble.midi(clip, 'c-major.mid');
```
2. then use node.js to run this ^ in the terminal to generate a MIDI file called "c-major.mid"
3. manually bring it into Ableton Live on a channel. 

Is your feature trying to get rid off step 2 and 3 such that users can drag an instance of scribblemax-node-scribbletune-template.amxd and directly write some code inside dist/nodeScribbletune.js and then use some UI element in the amxd to generate the clip in Ableton?

Please let me know if my understanding is correct. 

One other confusion I have is, the UI of the template amxd shows 2 dropdowns with few parameters. How will a JS developer customize what they want to send to dist/nodeScribbletune.js? For example, the patterns dropdown has `xxxx` and `x_xx` as patterns. 

amxd

I m curious to know how would I use some other pattern, for eg. `xRxx` or another set of notes OR how would I be able to use some of the other parameters of the clip method.

**Comment by JanZaion** [comment]
@walmik I think you've accurately described most of my original intention. My goal was to help developers who know both JS and Max for Live by making a pipeline from Live's UI to Node for Max and then from Node for Max to Scribblemax and consequently to Live's API.

I will try to describe a use case in a project of mine. I wanted to use Tonal's music theory methods like transposing a note, getting a pitch of a note etc with Scribbletune's clip method, mainly because the pattern language is just such a great way to generate rhythmical patterns. Doing it all in Node was my initial method, but I had to do it like you've described in step 2 and 3. That was very annoying and it totally took me out of the creative flow when trying to do something musical. But hey, great news for me, Scribblemax exists! Bundling everything together with Webpack kept crashing Max and was just a no go, so I had to figure out the pipeline from the UI to Node to Live. It took me several sittings and a lot of trial and error to figure it out. I thought I might share my solution and maybe someone else could use it and save their time.

That being said, your questions raise some interesting points that didn't occur to me before. My intended audience were M4L/JS developers, but what about JS developers who own M4L license and have no intention of learning M4L? It's basically what the .amxd does once you delete the UI elements.

About those UI elements you are asking about, they are there simply as placeholders, as an illustration of how to get data from UI to Node for Max. You can use whatever pattern is accepted by the clip method. For instance, if you want to extend the dropdown menu, you can do so via M4L's inspector view. I don't know how well you know your way around M4L, I'd be happy to provide some directions if you have any questions. 

The file nodeScribbletune.js is meant to be extended just like you say. Perhaps my initial commit is too confusing and it would be better to distribute an .amxd file with fixed UI.


About making it all work: I've realised that, distributing a frozen device as a template makes no sense. I've deleted the scribblemax-node-scribbletune-template.amxd file and made a new one, NodeMaxScribbletuneTemplate.amxd. You can find it in my latest commit. There are installation notes inside the device. Scribbletune should be installed via `script npm install` command from within the device, so please make sure you have the original package.json located in the same file. Downloading the latest version of my branch of Scribblemax should be enough for all the files to be in the right place.

**Comment by walmik** [comment]
Apologies for the delay @JanZaion I ve been very busy at work, however I ll get some quality time starting 04/14. In the mean time I ll pull in your new changes and try out this weekend.

**Comment by JanZaion** [comment]
@walmik no worries, please let me know if I should clarify anything

**Comment by walmik** [comment]
@JanZaion I m really sorry for the delay in reviewing this PR (i finally found some time in the last coupla days!) I think i ve fully understood what this change is about. I believe it s more of a "template" device than a actually used device (please correct me if i m wrong)

**Comment by walmik** [comment]
@JanZaion I have an idea around this. We should have a script that "generates" all the files that are needed for creating a new device with Scribbletune. Basically whatever you ve commited as files in this PR -> a script should generate them (the base files can continue to reside at a separate location in the same project). Hope that makes sense. I ll do these changes later (you are welcome to make them too) but for now lets merge this in and I ll create a page on scribbletune.com for "getting started" in the mean time (later a script can do all the steps and generate a starting point device/JS files for people to make their own devices)

Thank you very much for putting in so much effort into this (I noted all the comments within the file as well as the device itself)!

**Comment by JanZaion** [comment]
@walmik Im glad you found my PR suitable for merging! If I understand your idea correctly, you want to make the starting point for making a Max device as easy as running a single command that runs the script. That would be a very smooth starting point. Ill definitely give it some thought!

**Comment by JanZaion** [comment]
Just a small note, please delete the "scribblemax-node-scribbletune-template.amxd" file from the src folder. "NodeMaxScribbletuneTemplate.maxpat" is the final version and I probably forgot to delete the "scribblemax-node-scribbletune-template.amxd" during my commits.

**Comment by walmik** [comment]
@JanZaion thank you, i ll clean that up :)

**Pull request merged**
